authenticator/urls.py
from django.urls import path
from . import views

# app_name = 'authenticator'

urlpatterns = [
    path('', views.index, name='index'),
    # path('accounts/login/', views.login_view, name='login'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('<int:test_id>/results/', views.mark_test, name='mark'),
    path('<int:test_id>/test/', views.test_questions, name='test_questions'),
    path('show_results/', views.view_results, name='results'),
    path('result_viewer/', views.results_viewer, name='results_viewer'),
    path('rv_login/', views.rv_login, name='rv_login'),
    # path('export_results/', views.export_results, name='export_results'),

]

cbtx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authenticator.urls')),
    # path('test/', include('tester.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authenticator/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django import forms


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None):
        user = self.model(username=username)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password):
        user = self.create_user(username, password)
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    classes = models.CharField(max_length=50)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['password']

    objects = CustomUserManager()

    def __str__(self):
        return self.username


class Class(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Test(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='course/')
    # taken = models.BooleanField(default=False)
    # description = name = models.CharField(max_length=200)
    classes = models.ForeignKey(Class, on_delete=models.CASCADE)
    written_by = models.ManyToManyField(CustomUser, related_name='written_tests')

    def __str__(self):
        return self.name

class Question(models.Model):
    question_text = models.CharField(max_length=500)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    A = models.CharField(max_length=100)
    B = models.CharField(max_length=100)
    C = models.CharField(max_length=100)
    D = models.CharField(max_length=100)
    correct_option = models.CharField(max_length=100)

    def __str__(self):
        return self.question_text


class TestResult(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    svc_no = models.CharField(max_length=100)
    score = models.IntegerField()
    classes = models.CharField(max_length=50)
    desc = models.CharField(max_length=50)
    date = models.DateTimeField('date submitted')

    def __str__(self):
        return f"{str(self.user)} {self.test.name} Test Result"

authenticator/forms.py
from django import forms
from .models import CustomUser
from django.forms.utils import ErrorList


class NameForm(forms.ModelForm):
    CHOICES = (
        ('SCIENCE', 'SCIENCE'),
        ('ART', 'ART'),
    )

    classes = forms.ChoiceField(choices=CHOICES, widget=forms.Select(attrs={'placeholder': 'Select a class'}))

    class Meta:
        model = CustomUser
        fields = ('username', 'password', 'classes')
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Enter your username'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Enter your password'}),
        }

        labels = {
            'username': False,
            'password': False,
        }

authenticator/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.views.decorators.cache import never_cache
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import NameForm
from .models import CustomUser, Question, Test, TestResult, Class
from django.views.decorators.csrf import csrf_protect, csrf_exempt
import datetime
from django.utils import timezone
from django.contrib import messages

import openpyxl
from django.http import HttpResponse

now = timezone.now()

from django.contrib.sessions.models import Session
from django.contrib.auth import get_user_model
from django.db.models import Q


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = NameForm()

    context = {
        'error': 'Something went wrong',
        'form': form
    }

    return render(request, 'authenticator/register.html', context)


# @login_required
User = get_user_model()


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            # Check if the user has an active session on another device
            active_sessions = Session.objects.filter(Q(expire_date__gte=timezone.now()) | Q(expire_date=None))
            for session in active_sessions:
                session_data = session.get_decoded()
                session_user_id = session_data.get('_auth_user_id')
                if session_user_id is not None and user.id == int(session_user_id):
                    # Another active session found, prevent login
                    context = {'error': 'You are already logged in on another device.'}
                    return render(request, 'authenticator/login.html', context)

            # Log in the user and create a new session
            login(request, user)
            return redirect('dashboard')
        else:
            context = {'error': 'Invalid username or password'}
            return render(request, 'authenticator/login.html', context)
    else:
        return render(request, 'authenticator/login.html')


def index(request):
    return render(request, 'authenticator/index.html')


# result viewer login
def rv_login(request):
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('results_viewer')
        else:
            context = {'error': 'Invalid username or password'}
            return render(request, 'authenticator/rvlogin.html', context)
    else:
        return render(request, 'authenticator/rvlogin.html')


# v 0.6
@login_required(login_url='/login/')
def dashboard(request):
    if request.user.is_authenticated:
        # render the test page
        # tests = Test.objects.all()

        classes = Class.objects.all()
        selected_class = request.user.classes

        # display the test based on science or art student
        if selected_class == "SCIENCE":
            tests = Test.objects.filter(classes__id=1).order_by('name')
        else:
            tests = Test.objects.filter(classes__id=2).order_by('name')

        written_tests = Test.objects.filter(written_by=request.user)

        context = {
            'tests': tests,
            'written_tests': written_tests,
            'name': request.user.username,
        }

        return render(request, 'authenticator/dashboard.html', context)
    else:
        return redirect('login')


def test_questions(request, test_id):
    if request.user.is_authenticated:
        tests = Test.objects.get(id=test_id)
        tests_question = get_object_or_404(Test, pk=test_id)

        context = {
            'tests': tests,
            'test': tests_question,
            'name': request.user.username,
        }

        return render(request, 'authenticator/test.html', context)

    else:
        return redirect('login')


@csrf_exempt
def mark_test(request, test_id):
    if request.user.is_authenticated:

        tests_question = get_object_or_404(Test, pk=test_id)

        # Check if the user has already written the test
        # if tests_question.written_by.filter(pk=request.user.pk).exists():
        #     return redirect('results')  # Redirect to results page or any other appropriate action

        questions = Question.objects.all()
        results = TestResult
        score = 0

        for question in questions:
            if request.POST.get(str(question.id)) == question.correct_option:
                score += 1

        results.objects.create(
            test=tests_question,
            user=request.user,
            username=request.user.username,
            svc_no=request.user.password,
            score=score,
            classes=request.user.classes,
            desc=tests_question.name,
            date=now,
        )

        tests_question.written_by.add(request.user)  # Add the user to the written_by ManyToMany field
        tests_question.save()
        return redirect('results')

    else:
        return redirect('login')


def view_results(request):
    results = TestResult.objects.filter(user=request.user)
    context = {

        'results': results,

    }
    return render(request, 'authenticator/results.html', context)


@staff_member_required
@login_required(login_url='index')  # Redirects non-authenticated users to the login page
def results_viewer(request):
    results = TestResult.objects.all()

    if request.method == 'POST':

        # Extract variables to be used for querying the db
        search_name = request.POST.get('search_name')
        selected_class = request.POST.get('selected_class')
        selected_subject = request.POST.get('selected_subject')

        # Perform filtering based on the selected criteria
        # Assuming 'results' is a queryset of the queried results
        filtered_results = TestResult.objects.all()

        if search_name:
            filtered_results = results.filter(username__icontains=search_name)

        if selected_class != 'All' and selected_subject != 'All':
            filtered_results = results.filter(classes=selected_class, desc=selected_subject)

        if 'export' in request.POST:  # Check if the export button is clicked
            if filtered_results.exists():
                # Export the filtered results to Excel
                wb = openpyxl.Workbook()
                ws = wb.active

                # Write column headers
                ws['A1'] = 'User'
                ws['B1'] = 'Test'
                ws['C1'] = 'Classes'
                ws['D1'] = 'Score'

                # Write filtered results to rows
                row_num = 2
                for result in filtered_results:
                    ws.cell(row=row_num, column=1, value=result.username)
                    ws.cell(row=row_num, column=2, value=result.desc)
                    ws.cell(row=row_num, column=3, value=result.classes)
                    ws.cell(row=row_num, column=4, value=result.score)
                    row_num += 1

                # Set response headers for Excel file download
                response = HttpResponse(
                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
                response['Content-Disposition'] = 'attachment; filename=exported_results.xlsx'

                # Save the workbook to the response
                wb.save(response)

                return response

        # Return the filtered results to the template or No results found
        if filtered_results.exists():
            context = {
                'results': filtered_results,
            }
        else:
            context = {
                'results': None,
                'not_found_message': 'No results found.',
            }

            return render(request, 'authenticator/results_viewer.html', context)

        return render(request, 'authenticator/results_viewer.html', context)

    else:
        context = {

            'results': results,

        }
        return render(request, 'authenticator/results_viewer.html', context)


def logout_view(request):
    logout(request)
    return redirect('index')

authenticator/templates/authenticator/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Dashboard</title>
    <link type="text/css" href="{% static 'style/dashboard.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet" />
    <link type="image/x-icon" href="{% static 'img/afit.ico' %}" rel="icon" />
    <script src="{% static 'js/timer.js' %}"></script>

    <script>
        // Replace the current state with a new state
        window.history.replaceState(null, document.title, window.location.href);

        // Add a listener for the 'popstate' event
        window.addEventListener('popstate', function(event) {
          // Push a new state to forward the user to the next page again
          window.history.pushState(null, document.title, window.location.href);
        });

    </script>

</head>
<body>


    <div id="main">
        <div id="header">

            <div class="header_wrap">
            <!--<h4>Computer Based Test: Python {{ test.name }} </h4>-->
                <div class="logo">
                    <img src="{% static 'img/afit.png' %}" alt="AFIT Logo" />
                </div>

                <a href="{% url 'logout' %}">
                    <button class="head-btn">Log Out</button>
                </a>

            </div>

        </div>

        <div class="head-pad"></div>

        <h2>Welcome, <strong style="color:#088ccd;">{{ name }}</strong> choose your Assessment</h2>

        <div class="test-title">
            <h4>Please read the Instructions very carefully</h4>

            <ol>
                <li> Always logout! to prevent account loss.</li>
                <li> Do not close the browser!</li>
                <li> Do not try to hack our systems :)</li>
            </ol>

        </div>



        <div class="test-container">
        {% for test in tests %}
            <div class="test-card">

                <center>

                    <img src="{{ test.image.url }}" />
                    <h3>{{ test.name }}</h3>
                    {% if test in written_tests %}
                        <button class="sec-btn" disabled>Written</button>
                    {% else%}
                    <a href="{% url 'test_questions' test.id %}">
                        <button id="write-btn" class="sec-btn" >Write</button>
                    </a>
                    {% endif %}
                </center>

            </div>

        {% endfor %}

        </div>

    <h4 style="color:#3f0e40;">Cbt v0.8 4 AFIT : Developed by Akintola Technologies</h4>
    </div>

</body>
</html>

authenticator/templates/authenticator/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Computer Based Test</title>
    <link type="image/x-icon" href="{% static 'img/afit.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'style/dashboard.css' %}" rel="stylesheet"/>

    <script>
        window.onload = function(){
                window.localStorage.clear()
        };

        //Prevent Data
        history.pushState(null, null, );
        window.addEventListener('popstate', function(event) {
            history.pushState(null, null, );
        });

    </script>

</head>
<body>
<!--    <a href="{% url 'rv_login' %}">-->
<!--        <div class="util">-->
<!--            <img src="{% static 'img/results.svg' %}" alt="#"  />-->
<!--        </div>-->
<!--    </a>-->

    {% csrf_token %}

    <div id="container">

            <div class="dialogue">
                <center>
                    <img src="{% static 'img/afit.png' %}" alt="AFIT Logo" />
                    <h2>SBRS OSOGBO WEEKLY TEST</h2>
                     <p>To Evaluate students for the week under review.</p>

                    <a href="{% url 'login' %}"><button class="sec-btn">Log in</button></a>
                    <a href="{% url 'register' %}"><button>Register</button></a>
                </center>
            </div>
    </div>

</body>
</html>

authenticator/templates/authenticator/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login to CBT</title>
    <link type="image/x-icon" href="{% static 'img/afit.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet"/>
</head>
<body>

    <div id="container">

        <div class="dialogue">

            <form method="post">

                {% if error %}
                    <p style="color:red;">{{ error }}</p>
                {% endif %}

                {% csrf_token %}
                <h1>Login</h1>
                <input type="text" name="username" id="username" placeholder="Enter your name">
                <input type="password" name="password" id="password" placeholder="Enter your pin">
                <button>Login</button>
                 <p>Register here before Log in ! <a href="{% url 'register' %}">Register</a></p>

            </form>


        </div>




    </div>




</body>
</html>

authenticator/templates/authenticator/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

     <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link type="image/x-icon" href="{% static 'img/afit.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet"/>
</head>
<body>


    <div id="container">

        <div class="dialogue">

            <form method="post">
                <h1>Register</h1>
                {% csrf_token %}
                {{ form }}
                <button>Submit</button>
                <p>Already Registered ? <a href="{% url 'login' %}">Login</a></p>
            </form>

        </div>

    </div>



</body>
</html>

authenticator/templates/authenticator/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
    <link type="image/x-icon" href="{% static 'img/afms logo.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'style/dashboard.css' %}" rel="stylesheet"/>

<!--    <script src="{% static 'js/timer.js' %}"></script>-->
    <script>
        window.onload = function(){
            window.localStorage.clear()
        };

        //Prevent Data
    history.pushState(null, null, );
    window.addEventListener('popstate', function(event) {
      history.pushState(null, null, );
    });

    </script>

    <script>
        // Replace the current state with a new state
        window.history.replaceState(null, document.title, window.location.href);

        // Add a listener for the 'popstate' event
        window.addEventListener('popstate', function(event) {
          // Push a new state to forward the user to the next page again
          window.history.pushState(null, document.title, window.location.href);
        });

    </script>

</head>
<body>

    <div id="main">


            <center style="margin-top: 60px;">

                {%  for itm in results %}
                <img src="{% static 'img/check.png' %}" alt="" width="200px"/>
                <h1>Congrats {{  itm.user }} </h1>
                <p>
                    You have successfully written the {{ itm.test }} Test  <br/>
                    you scored <br/>
                    <h1 class="score" style="color: green;"> {{ itm.score }} / 10 </h1>
                </p>
                {% endfor %}

            </center>



            <a href="{% url 'dashboard' %}"><button>Go To Dashboard</button></a>

    </div>

    <script>
        let score = document.querySelector(".score");
        if(parseInt(score.textContent) < 5){
            score.style.color = "red";
        }

        console.log("wired", typeof(parseInt(score.textContent)));
    </script>

</body>
</html>

authenticator/templates/authenticator/results_viewer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results Viewer</title>
    <link type="image/x-icon" href="{% static 'img/afit.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'style/dashboard.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'style/result.css' %}" rel="stylesheet"/>

</head>
<body>

    <div id="main">

            <div id="header">

                <div class="header_wrap">
                <!--<h4>Computer Based Test: Python {{ test.name }} </h4>-->
                    <div class="logo">
                        <img src="{% static 'img/afit.png' %}" alt="AFIT Logo" />
                    </div>

                    <a href="{% url 'index' %}">
                        <button class="head-btn">Log Out</button>
                    </a>

                </div>

            </div>

            <div style="margin-bottom: 100px;">

            </div>

            <form method="POST" style="padding:0;">
                {% csrf_token %}
                <input name="search_name" type="text" placeholder="Search by name" />
                <p>Select Class</p>
                <select name="selected_class">
                    <option value="All">All</option>
                    <option value="ART">ART</option>
                    <option value="SCIENCE">SCIENCE</option>
                </select>

                <p>Select Subject</p>
                <select name="selected_subject">
                    <option value="All">All</option>
                    <option value="USE OF ENGLISH (SCIENCE)">USE OF ENGLISH(SCIENCE)</option>
                    <option value="USE OF ENGLISH (ARTS)">USE OF ENGLISH(ARTS)</option>
                    <option value="MATHEMATICS (SCIENCE)">MATHEMATICS(SCIENCE)</option>
                    <option value="MATHEMATICS (ARTS)">MATHEMATICS(ARTS)</option>
                    <option value="ECONOMICS(SCIENCE)">ECONOMICS(SCIENCE)</option>
                    <option value="ECONOMICS(ARTS)">ECONOMICS(ARTS)</option>
                    <option value="PHYSICS">PHYSICS</option>
                    <option value="GEOGRAPHY">GEOGRAPHY</option>
                    <option value="BIOLOGY">BIOLOGY</option>
                    <option value="CHEMISTRY">CHEMISTRY</option>
                    <option value="GOVERNMENT">GOVERNMENT</option>

                </select>

                <button class="sec-btn">Submit Query</button>


                <h1>Queried Results</h1>
                {% if results %}
                {%  for result in results %}
                <div class="result">
                    <div class="data">
                        <h4>{{  result.username }}</h4>
                        <h5>{{ result.test }}</h5>
                    </div>

                    <div class="data">
                        <h4>{{ result.classes}} </h4>
                        <h5>{{ result.score }}</h5>
                    </div>

                </div>
                {% endfor %}
                {% else %}
                <p>{{ not_found_message }}</p>
                {% endif %}

                <button name="export">Export All Results</button>
            </form>

    </div>

</body>
</html>

authenticator/templates/authenticator/rvlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login to Result Viewer</title>
    <link type="image/x-icon" href="{% static 'img/afms logo.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet"/>

</head>
<body>


    <div id="container">

        <div class="dialogue">

            <form method="post">

                {% if error %}
                    <p style="color:red;">{{ error }}</p>
                {% endif %}

                {% csrf_token %}
                <center>
                    <img src="{% static 'img/quest.png' %}" alt="AFMS Logo" width="260px"/>
                    <h2>Results Viewer</h2>
                </center>
                 <input type="text" name="username" id="username" placeholder="Enter name">
                 <input type="text" name="password" id="password" placeholder="Enter Password">
                 <button style="background-color: #ffb548;">Login</button>
                 <p>Oops only for admins ! <a href="{% url 'index' %}">Go Home</a></p>

            </form>


        </div>




    </div>



</body>
</html>

authenticator/templates/authenticator/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ongoing Exam</title>
    <link type="image/x-icon" href="{% static 'img/afit.ico' %}" rel="icon" />
    <link type="text/css" href="{% static 'style/dashboard.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'style/styles.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/timer.js' %}"></script>


</head>
<body>


    <div id="main">
        <div id="header">

            <div class="header_wrap">
                <h4>Weekly Test: {{ tests.name }} </h4>

                <div class="timer">
                    <div class="icn">
                        <img src="{% static 'img/timer.svg' %}"/>
                    </div>
                    <span id="time" style="font-weight: 800;"></span>
                </div>
            </div>

        </div>
        <div class="head-pad"></div>

        <h2>Welcome <strong style="color:#088ccd;">{{ name }}</strong></h2>

        <div class="test-title">
            <h4>Please read the Instructions very carefully</h4>
            <ol>
                <li> Select the most suitable answer from the options
                    lettered A – D. Answer all questions.</li>
            </ol>
        </div>

        {% for question in test.question_set.all %}
        <p style="font-weight: bolder;"><strong>{{ forloop.counter }}</strong> {{ question.question_text }}</p>
        <form action="{% url 'mark' test.id %}" method="post" name="test">
            {% csrf_token %}
            <span style="margin-right: 20px;"></span>A.<input type="radio" name="{{ question.id }}" value="{{ question.A }}" style="cursor: pointer;">{{ question.A }}<br>
            <span style="margin-right: 20px;"></span>B.<input type="radio" name="{{ question.id }}" value="{{ question.B }}" style="cursor: pointer;">{{ question.B }}<br>
            <span style="margin-right: 20px;"></span>C.<input type="radio" name="{{ question.id }}" value="{{ question.C }}" style="cursor: pointer;">{{ question.C }}<br>
            <span style="margin-right: 20px;"></span>D.<input type="radio" name="{{ question.id }}" value="{{ question.D }}" style="cursor: pointer;">{{ question.D }}<br>
            <hr style="opacity: 0.2;"/>

        {% endfor %}
            <button>Submit this Test</button>
        </form>

    </div>



</body>
</html>